---
- hosts: ansible
  connection: local
  tasks:
  - name: Configure next boot override
    dellemc.openmanage.idrac_boot:
      idrac_ip: "172.16.143.14"
      idrac_user: "{{idrac_username}}"
      idrac_password: "{{idrac_password}}!"
      validate_certs: false
      boot_source_override_mode: uefi
      boot_source_override_target: cd
      boot_source_override_enabled: once
