---
- hosts: ansible
  connection: local
  tasks:
  - name: Configure time zone and NTP on iDRAC
    dellemc.openmanage.idrac_timezone_ntp:
        idrac_ip: "172.16.143.14"
        idrac_user: "{{idrac_username}}"
        idrac_password: "{{idrac_password}}!"
        validate_certs: false
        setup_idrac_timezone: "UTC"
        enable_ntp: Enabled
        ntp_server_1: "190.168.0.1"
        ntp_server_2: "190.168.0.2"
        ntp_server_3: "190.168.0.3"
