---
- hosts: ansible
  connection: local
  tasks:
  - name: View all volume details
    dellemc.openmanage.dellemc_idrac_storage_volume:
      idrac_ip: "{{item}}"
      idrac_user: "{{idrac_username}}"
      idrac_password: "{{idrac_password}}"
      validate_certs: false
      state: "view"
      